const fixtures = {
  stages: {
    scope: { n: "01", title: "Scope the claim", copy: "A merchant-safe brief defines the customer, questions, public sources, geography, time window, and what the run must not infer.", contract: "ResearchScope → topics[] · sources[] · guardrails[]" },
    collect: { n: "02", title: "Collect public traces", copy: "A replay shows direct public-page collection first, with coverage and failures made visible. No authentication bypass, private enrichment, or automated outreach.", contract: "SourceRecord → url · capturedAt · authorContext · text" },
    prove: { n: "03", title: "Preserve provenance", copy: "Snapshots are deduplicated and each claim remains traceable. A promotional post or a consumer complaint is not automatically a buyer-intent signal.", contract: "EvidenceItem → sourceRef · quote · classification · uncertainty" },
    model: { n: "04", title: "Find resilient patterns", copy: "Semantic clusters and momentum are estimates shaped by coverage. The view calls out fetch gaps so more collection is not mistaken for more demand.", contract: "Cluster → evidenceIds[] · momentumEstimate · relevanceScore" },
    test: { n: "05", title: "Recommend a next test", copy: "An opportunity card connects evidence to a cautious, falsifiable next step. It never claims a public post proves bot traffic, ROAS, or a root cause.", contract: "Opportunity → evidenceIds[] · proposedFit · confidence · nextTest" }
  },
  evidence: [
    { source: "PUBLIC COMMUNITY / SIMULATED", title: "Agency operator describes a lead-quality mismatch", quote: "We can make the platform dashboard look healthy, but the sales team says the conversations are getting less qualified.", context: "Fictional agency-operator context · first-person operational complaint", kind: "Observed complaint", fit: "Potential fit: connect campaign context to authorized CRM outcome definitions", uncertainty: "Does not establish a platform, tracking, or traffic-quality cause.", link: "https://example.com/simulated-source/lead-quality" },
    { source: "PUBLIC CREATOR THREAD / SIMULATED", title: "Merchant asks why purchase reporting changes after checkout", quote: "Our checkout totals and the ads manager do not tell the same story. I need a way to spot when the tracking breaks before a launch.", context: "Fictional merchant context · firsthand measurement frustration", kind: "Observed complaint", fit: "Potential fit: instrumented measurement QA and event-to-order reconciliation", uncertainty: "No access to store or pixel setup; cause is unknown.", link: "https://example.com/simulated-source/measurement" },
    { source: "PUBLIC FORUM / SIMULATED", title: "Small team reports media-buying workload strain", quote: "Every account gets a weekly hunt for weird attribution gaps. It is too much manual checking for a team of two.", context: "Fictional operator context · stated workflow pain", kind: "Observed complaint", fit: "Potential fit: alerting around authorized merchant outcomes and named research clusters", uncertainty: "A complaint alone does not show willingness to buy or budget authority.", link: "https://example.com/simulated-source/workload" }
  ],
  opportunities: [
    { badge: "82% SUPPORTED FIT", title: "Measurement friction watchlist", body: "Cluster public questions about attribution mismatches; pair them with an authorized merchant event-to-order reconciliation check.", evidence: "Evidence: 9 simulated first-person complaints · 2 coverage gaps", test: "Next test: validate whether merchants recognize the alert language in 5 discovery calls." },
    { badge: "76% SUPPORTED FIT", title: "Lead-quality briefing kit", body: "Turn stated downstream-quality pain into a research brief that keeps ad signals, CRM outcomes, and uncertainty visibly separate.", evidence: "Evidence: 7 simulated agency/operator complaints", test: "Next test: compare response to a CRM signal-mapping worksheet versus generic reporting copy." },
    { badge: "69% SUPPORTED FIT", title: "Creative fatigue evidence view", body: "Track observed public creative and creator activity over time without asserting spend, sales, or coordinated promotion.", evidence: "Evidence: 12 simulated observed creative snapshots", test: "Next test: ask buyers whether the time-series view changes their creative-review cadence." }
  ]
};

const stageDetail = document.getElementById('stageDetail');
const setStage = (key) => { const item = fixtures.stages[key]; stageDetail.innerHTML = `<span class="number">STAGE ${item.n}</span><h3>${item.title}</h3><p>${item.copy}</p><div class="contract">${item.contract}</div>`; document.querySelectorAll('.stage').forEach(b => { const selected = b.dataset.stage === key; b.classList.toggle('selected', selected); b.setAttribute('aria-pressed', String(selected)); }); };
const setView = (name) => { document.querySelectorAll('.view').forEach(v => v.classList.toggle('hidden', v.id !== name)); document.querySelectorAll('.nav-link').forEach(b => b.classList.toggle('active', b.dataset.view === name)); location.hash = name; window.scrollTo({top:0,behavior:'smooth'}); };
const showToast = (text) => { const toast = document.getElementById('toast'); toast.textContent = text; toast.classList.add('visible'); window.setTimeout(() => toast.classList.remove('visible'), 2600); };
const renderEvidence = (selected = 0) => { document.getElementById('evidenceList').innerHTML = fixtures.evidence.map((e,i) => `<button class="evidence-row ${i===selected?'active':''}" data-evidence="${i}"><span class="source">${e.source}</span><b>${e.title}</b><small>${e.context}</small></button>`).join(''); const e=fixtures.evidence[selected]; document.getElementById('evidenceDrawer').innerHTML = `<span class="kicker">${e.kind}</span><blockquote>“${e.quote}”</blockquote><a class="source-link" href="${e.link}" target="_blank" rel="noreferrer">Open illustrative source ↗</a><div class="detail-grid"><div><span>PROFESSIONAL CONTEXT</span><p>${e.context}</p></div><div><span>POSSIBLE CAPABILITY MATCH</span><p>${e.fit}</p></div><div><span>CONFIDENCE</span><b>Medium · classified first-person</b></div><div><span>UNCERTAINTY</span><p>${e.uncertainty}</p></div></div>`; document.querySelectorAll('[data-evidence]').forEach(b=>b.addEventListener('click',()=>renderEvidence(Number(b.dataset.evidence)))); };
const renderOpportunities = () => { document.getElementById('opportunityGrid').innerHTML = fixtures.opportunities.map(o => `<article class="opportunity-card"><span class="badge">${o.badge}</span><h3>${o.title}</h3><p>${o.body}</p><footer>${o.evidence}<br/><br/><strong>${o.test}</strong></footer></article>`).join(''); };

document.querySelectorAll('.stage').forEach(b => b.addEventListener('click', () => setStage(b.dataset.stage)));
document.querySelectorAll('.nav-link').forEach(b => b.addEventListener('click', () => setView(b.dataset.view)));
document.getElementById('capacity').addEventListener('input', (e) => { const n=e.target.value; document.getElementById('capacityOutput').textContent=`${n}M`; document.getElementById('uniqueCount').textContent=`${(n*.071).toFixed(1)}M`; });
document.getElementById('runReplay').addEventListener('click', () => { const status=document.getElementById('runStatus'); status.textContent='Simulating source coverage and provenance checks…'; document.getElementById('runReplay').disabled=true; window.setTimeout(()=>{status.textContent='Replay complete · 2 simulated fetch failures retained in coverage';document.getElementById('runReplay').disabled=false;document.getElementById('confidence').textContent='84%';showToast('Replay refreshed — no live collection ran.');},900); });
document.getElementById('resetDemo').addEventListener('click',()=>{document.getElementById('capacity').value=260;document.getElementById('capacity').dispatchEvent(new Event('input'));document.getElementById('runStatus').textContent='Replay loaded · no live collection';document.getElementById('confidence').textContent='82%';showToast('Replay reset.');});
setStage('scope'); renderEvidence(); renderOpportunities();
if (!Object.values(fixtures).every(Boolean)) throw new Error('Fixture contract failed');
if (location.hash && document.getElementById(location.hash.slice(1))) setView(location.hash.slice(1));
