import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { runProxyHarness } from './local-proxy-test.mjs';

const [html, header, css, js, sop] = await Promise.all(['index.html', 'partials/header.html', 'styles.css', 'app.js', 'SOPs/README.md'].map(file => readFile(file, 'utf8')));
const server = await readFile('local-server.mjs', 'utf8');
assert.match(header, /DEMO \/ FICTIONAL DATA/);
assert.match(html, /include virtual="\/partials\/header\.html"/);
assert.match(html, /aria-pressed="true"/);
assert.match(css, /prefers-reduced-motion/);
assert.match(js, /Fixture contract failed/);
assert.match(sop, /Local proxy harness/);
assert.match(server, /let body = await readFile/);
assert.match(server, /outsideRoot\.startsWith/);
assert.match(server, /renderSsi/);
const { stdout } = await promisify(execFile)('python3', ['api.py', '--self-test']);
assert.match(stdout, /API_SELF_TEST_PASS/);
const proxy = await runProxyHarness();
assert.ok(proxy.elapsedMs < 2000);
console.log(JSON.stringify({ status: 'PASS', uiFixtureContract: true, proxy }));
